server:
  port: 8080

jwt:
  sso:
    server:
      cookie:
        domain: localhost  #域名站点
        path: /                        #存放cookie路径
        max-age: 0                     #存活时间
  rsa:
    expire: 30 #过期时间,单位分钟
    pri-key-path: /rsa/rsa.pri
    secret: ufirelogin231231231321