server:
  port: 8080

jwt:
  sso:
    server:
      cookie:
        domain: localhost  #域名站点
        path: /                        #存放cookie路径
        max-age: 0                     #存活时间
rsa:
  key:
    pri:
      key-path: D:\ufire\ufire-jwt-sso-demo\auth-server\src\main\resources\key\rsa-jwt.pri
    pub:
      key-path: D:\ufire\ufire-jwt-sso-demo\auth-console\src\main\resources\key\rsa-jwt.pub
