auth-server: http://localhost:8080/

server:
  port: 8081
jwt:
  sso:
    client:
      client-id: console
      secret: 123456
      home-url: http://localhost:8081/
      access-token-url: ${auth-server}access_token
      refresh-token-url: ${auth-server}refresh_token
      authorize-url: ${auth-server}authorize
