auth-server: http://localhost:8080/

server:
  port: 8081
jwt:
  sso:
    client:
      client-id: console
      secret: 123456
      home-url: http://localhost:8081/
      access-token-url: http://localhost:8080/access_token
      refresh-token-url: http://localhost:8080/refresh_token
      authorize-url: http://localhost:8080/authorize
      sso-url: http://localhost:8080/
rsa:
  key:
    pub:
      key-path: D:\ufire\ufire-jwt-sso-demo\auth-console\src\main\resources\key\rsa-jwt.pub