auth-server: http://sso.ufiredong.cn

server:
  port: 8080
jwt:
  sso:
    client:
      client-id: clienta
      secret: 123456
      home-url: http://clienta.ufiredong.cn
      access-token-url: ${auth-server}access_token
      refresh-token-url: ${auth-server}refresh_token
      authorize-url: ${auth-server}authorize
      sso-url: http://sso.ufiredong.cn/
    server:
      cookie:
        path: /
        domain: ufiredong.cn
    refresh-token:
      refresh-token: eyJhbGciOiJSUzI1NiJ9.eyJ1c2VyIjoiY2xpZW50IiwianRpIjoiWmpsbFpURTBOMll0WWpJd055MDBaakkwTFdJek9URXRZbVk0WWpVek9EVm1NelUyIiwiZXhwIjoxNjQwMDMzMDEwfQ.DIZds4vh-MeT-ON7gJ5t-Jaa1o3nj_Ve9hTzd97UpHqCELlc3rcL-K3avnwM2ZHtEAL_QRGSdq_oY_nbMLAakvxLSyUTbLkZ9k9ggz9sBT7cOBiB5HLMtGRa2NKx5SlfZI8yzxFVYjQAEbSDxAVPeAhjFXSoB1EixZ-Z-kmQkf8xQ-MJSXPTldBF8j0t0o_P55IIbq2-cL3vghjmSWjRlibnLUuyz_fsL9nz1VDNjrZv5LAnlFTeit12VoJCWue_oBXYvbW_sorTgAPHe6woQHumEssMuguY8bjE-Lycuyw4Jon54uFlHEnjr05Yynswk8npzr41hQITf2Cn7V0v8Q
#rsa:
#  key:
#    pub:
#      key-path: D:\ufire\ufire-jwt-sso-demo\auth-client\src\main\resources\key\rsa-jwt.pub